---
- hosts: all
  tasks:

    - name: dump instance Name
      debug:
        var: hostvars[inventory_hostname].ec2_tag_Name

    - name: get java version
      command: java -fullversion
      become: true
      become_user: jenkins
      register: java_version_cmd
    - name: dump java version command output
      debug:
        var: java_version_cmd.stderr
    - set_fact:
        java_version: "{{ java_version_cmd.stderr | regex_replace('.*\"(.*)\".*', '\\1') }}"
    - name: verify java version
      assert:
        that:
          java_version | version_compare('1.8', '>=')
